name: Docker Image CI

on:
  push:
    branches: 
     - main
  pull_request:
    branches: 
     - main

jobs:

  build:
    name: build a image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ncat:$(date +%s)
    #- name: Login DockerHub
    #  uses: actions/
    - name: Test
      uses: aaaa777/docker-netcat@v1
